function glow(){
        if(n1===1){
            w1.shapeColor=("pink");
        }
        if(n1===2){
            w2.shapeColor=("pink");
        }
        if(n1===3){
            w3.shapeColor=("pink");
        }
        if(n1===4){
            w4.shapeColor=("pink");
        }
        if(n1===5){
            w5.shapeColor=("pink");
        }
        if(n1===6){
            w6.shapeColor=("pink");
        }
        if(n1===7){
            w7.shapeColor=("pink");
        }
        if(n1===8){
            w8.shapeColor=("pink");
        }
        if(n1===9){
            w9.shapeColor=("pink");
        }
        if(n1===10){
            w10.shapeColor=("pink");
        }
        if(n1===11){
            w11.shapeColor=("pink");
        }
        if(n1===12){
            w12.shapeColor=("pink");
        }
        if(n1===13){
            w13.shapeColor=("pink");
        }
        if(n1===14){
            w14.shapeColor=("pink");
        }
        if(n1===15){
            w15.shapeColor=("pink");
        }
        if(n1===16){
            w16.shapeColor=("pink");
        }
        if(n1===17){
            w17.shapeColor=("pink");
        }
        if(n1===18){
            w18.shapeColor=("pink");
        }
        if(n1===19){
            w19.shapeColor=("pink");
        }
        if(n1===20){
            w20.shapeColor=("pink");
        }
        if(n1===21){
            w21.shapeColor=("pink");
        }
        if(n1===22){
            w22.shapeColor=("pink");
        }
        if(n1===23){
            w23.shapeColor=("pink");
        }
        if(n1===24){
            w24.shapeColor=("pink");
        }
        if(n1===25){
            w25.shapeColor=("pink");
        }
        if(n1===26){
            w26.shapeColor=("pink");
        }
        if(n1===27){
            w27.shapeColor=("pink");
        }
        if(n1===28){
            w28.shapeColor=("pink");
        }
        if(n1===29){
            w29.shapeColor=("pink");
        }
        if(n1===30){
            w30.shapeColor=("pink");
        }
        if(n1===31){
            w31.shapeColor=("pink");
        }
        if(n1===32){
            w32.shapeColor=("pink");
        }
        if(n1===33){
            w33.shapeColor=("pink");
        }
        if(n1===34){
            w34.shapeColor=("pink");
        }
        if(n1===35){
            w35.shapeColor=("pink");
        }
        if(n1===36){
            w36.shapeColor=("pink");
        }
        if(n1===37){
            w37.shapeColor=("pink");
        }
        if(n1===38){
            w38.shapeColor=("pink");
        }
        if(n1===39){
            w39.shapeColor=("pink");
        }
        if(n1===40){
            w40.shapeColor=("pink");
        }
        if(n1===41){
            w41.shapeColor=("pink");
        }
        if(n1===42){
            w42.shapeColor=("pink");
        }
        if(n1===43){
            w43.shapeColor=("pink");
        }
        if(n1===44){
            w44.shapeColor=("pink");
        }
        if(n1===45){
            w45.shapeColor=("pink");
        }
        if(n1===46){
            w46.shapeColor=("pink");
        }
        if(n1===47){
            w47.shapeColor=("pink");
        }
        if(n1===48){
            w48.shapeColor=("pink");
        }
        if(n1===49){
            w49.shapeColor=("pink");
        }
        if(n1===50){
            w50.shapeColor=("pink");
        }
        if(n1===51){
            w51.shapeColor=("pink");
        }
        if(n1===52){
            w52.shapeColor=("pink");
        }
        if(n1===53){
            w53.shapeColor=("pink");
        }
        if(n1===54){
            w54.shapeColor=("pink");
        }
        if(n1===55){
            w55.shapeColor=("pink");
        }
        if(n1===56){
            w56.shapeColor=("pink");
        }
        if(n1===57){
            w57.shapeColor=("pink");
        }
        if(n1===58){
            w58.shapeColor=("pink");
        }
        if(n1===59){
            w59.shapeColor=("pink");
        }
        if(n1===60){
            w60.shapeColor=("pink");
        }
        if(n1===61){
            w61.shapeColor=("pink");
        }
        if(n1===62){
            w62.shapeColor=("pink");
        }
        if(n1===63){
            w63.shapeColor=("pink");
        }
        if(n1===64){
            w64.shapeColor=("pink");
        }
        if(n1===65){
            w65.shapeColor=("pink");
        }
        if(n1===66){
            w66.shapeColor=("pink");
        }
        if(n1===67){
            w67.shapeColor=("pink");
        }
        if(n1===68){
            w68.shapeColor=("pink");
        }
        if(n1===69){
            w69.shapeColor=("pink");
        }
        if(n1===70){
            w70.shapeColor=("pink");
        }
        if(n1===71){
            w71.shapeColor=("pink");
        }
        if(n1===72){
            w72.shapeColor=("pink");
        }
        if(n1===73){
            w73.shapeColor=("pink");
        }
        if(n1===74){
            w74.shapeColor=("pink");
        }
        if(n1===75){
            w75.shapeColor=("pink");
        }
        if(n1===76){
            w76.shapeColor=("pink");
        }
        if(n1===77){
            w77.shapeColor=("pink");
        }
        if(n1===78){
            w78.shapeColor=("pink");
        }
        if(n1===79){
            w79.shapeColor=("pink");
        }
        if(n1===80){
            w80.shapeColor=("pink");
        }
        if(n1===81){
            w81.shapeColor=("pink");
        }
        if(n1===82){
            w82.shapeColor=("pink");
        }
        if(n1===83){
            w83.shapeColor=("pink");
        }
        if(n1===84){
            w84.shapeColor=("pink");
        }
        if(n1===85){
            w85.shapeColor=("pink");
        }
        if(n1===86){
            w86.shapeColor=("pink");
        }
        if(n1===87){
            w87.shapeColor=("pink");
        }
        if(n1===88){
            w88.shapeColor=("pink");
        }
        if(n1===89){
            w89.shapeColor=("pink");
        }
        if(n1===90){
            w90.shapeColor=("pink");
        }
        if(n1===91){
            w91.shapeColor=("pink");
        }
        if(n1===92){
            w92.shapeColor=("pink");
        }
        if(n1===93){
            w93.shapeColor=("pink");
        }
        if(n1===94){
            w94.shapeColor=("pink");
        }
        if(n1===95){
            w95.shapeColor=("pink");
        }
        if(n1===96){
            w96.shapeColor=("pink");
        }
        if(n1===97){
            w97.shapeColor=("pink");
        }
        if(n1===98){
            w98.shapeColor=("pink");
        }
        if(n1===99){
            w99.shapeColor=("pink");
        }
        if(n1===100){
            w100.shapeColor=("pink");
        }

}